---
title: "School 3 - Race"
---

Data from <a href = "http://www.cpc.unc.edu/projects/addhealth">Add Health Wave 1</a>:

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, error = FALSE, warning = FALSE}
options(stringsAsFactors = F)


nodes <- read.csv("AddHealth3Att.csv", header=T, as.is=T)
links <- read.csv("AddHealth3Edge.csv", header=T, as.is=T)

library(visNetwork)

nodes$Race <- as.factor(nodes$Race)

nodes$shape <- "dot"
nodes$shadow <- TRUE
nodes$label <- nodes$id
nodes <- merge(nodes, as.data.frame(table(links$to)), by.x = "id", by.y = "Var1", all.x = TRUE)
nodes$Freq[is.na(nodes$Freq) == TRUE]  <- 0
nodes$size <- (nodes$Freq) ^ (7/4)

nodes$title <- paste0("<p>Race: ", nodes$Race, "<br>",
                      "Degree: ", nodes$Freq,"</p>")
nodes$borderWidth <- 2
nodes$color.background <- c("yellow", "orange", "green", "lightblue")[nodes$Race]
nodes$color.border <- nodes$color.background
nodes$color.highlight.background <- "orange"
nodes$color.highlight.border <- "darkred"
nodes$font.size <- 50
nodes$group <- nodes$Race


visNetwork(nodes, links) %>%
  visOptions(highlightNearest = TRUE, 
             selectedBy = "Race") %>%
  visGroups(groupname = "White", color = "lightblue") %>%
  visGroups(groupname = "American Indian", color = "yellow") %>%  
  visGroups(groupname = "Not Listed", color = "orange") %>%  
  visGroups(groupname = "Other", color = "green") %>%  
              visLegend()
```
